### PR TITLE
Added converter.py and json files

### PR DESCRIPTION
**Pull request by sagarkar10**
@lukehollis Please Review this PR. Thanks

### CODE REVIEW

**Comment by kylepjohnson** [comment]
@sagarkar10 Can you explain what this change does?

**Comment by sagarkar10** [comment]
This change has been made to make the text in perticular json format as required by the cltk front-end. The converter.py takes the plain text and structure it into a json in the cltk_json folder.
Please let me know if that answer your question. @kylepjohnson

**Comment by kylepjohnson** [comment]
Thanks.

**Comment by sagarkar10** [comment]
Welcome Sir

**Pull request merged**
